# Generated by Django 6.0.4 on 2026-04-19 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_service_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='icon',
            field=models.CharField(blank=True, default='stethoscope', help_text='Lucide icon name (e.g., Stethoscope, Heart)', max_length=50, verbose_name='icon'),
        ),
    ]
