# Generated by Django 6.0.4 on 2026-04-12 04:53

import django.db.models.deletion
import phonenumber_field.modelfields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Clinic',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='slug')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='phone')),
                ('website', models.URLField(blank=True, verbose_name='website')),
                ('street', models.CharField(max_length=255, verbose_name='street')),
                ('number', models.CharField(max_length=20, verbose_name='number')),
                ('complement', models.CharField(blank=True, max_length=100, verbose_name='complement')),
                ('neighborhood', models.CharField(max_length=100, verbose_name='neighborhood')),
                ('city', models.CharField(max_length=100, verbose_name='city')),
                ('state', models.CharField(max_length=100, verbose_name='state')),
                ('zip_code', models.CharField(max_length=20, verbose_name='zip code')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='clinics/logos/', verbose_name='logo')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='clinics/covers/', verbose_name='cover image')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('active', 'Activa'), ('suspended', 'Suspendida'), ('inactive', 'Inactiva')], default='pending', max_length=20, verbose_name='status')),
                ('opening_time', models.TimeField(default='08:00', verbose_name='opening time')),
                ('closing_time', models.TimeField(default='18:00', verbose_name='closing time')),
                ('appointment_duration', models.PositiveIntegerField(default=30, verbose_name='appointment duration (minutes)')),
                ('max_appointments_per_day', models.PositiveIntegerField(default=50, verbose_name='max appointments per day')),
                ('allow_online_booking', models.BooleanField(default=True, verbose_name='allow online booking')),
                ('rating', models.DecimalField(decimal_places=1, default=0.0, max_digits=2)),
                ('review_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admins', models.ManyToManyField(limit_choices_to={'user_type__in': ['clinic_admin', 'super_admin']}, related_name='managed_clinics', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'clinic',
                'verbose_name_plural': 'clinics',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClinicImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='clinics/gallery/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='clinics.clinic')),
            ],
            options={
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('license_number', models.CharField(max_length=50, verbose_name='license number')),
                ('bio', models.TextField(blank=True, verbose_name='biography')),
                ('education', models.TextField(blank=True, verbose_name='education')),
                ('experience_years', models.PositiveIntegerField(default=0, verbose_name='years of experience')),
                ('schedule', models.JSONField(default=dict, help_text='Format: {"monday": [{"start": "09:00", "end": "17:00"}], ...}', verbose_name='schedule')),
                ('consultation_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='consultation fee')),
                ('status', models.CharField(choices=[('active', 'Activo'), ('inactive', 'Inactivo'), ('on_vacation', 'De Vacaciones')], default='active', max_length=20, verbose_name='status')),
                ('rating', models.DecimalField(decimal_places=1, default=0.0, max_digits=2)),
                ('review_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctors', to='clinics.clinic')),
            ],
            options={
                'verbose_name': 'doctor',
                'verbose_name_plural': 'doctors',
                'ordering': ['-created_at'],
            },
        ),
    ]
