# Generated by Django 6.0.4 on 2026-04-19 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinic',
            name='phone',
            field=models.CharField(max_length=20, verbose_name='phone'),
        ),
    ]
