# Generated by Django 6.0.4 on 2026-04-12 04:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(max_length=50)),
                ('previous_status', models.CharField(blank=True, max_length=20)),
                ('new_status', models.CharField(blank=True, max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'appointment history',
                'verbose_name_plural': 'appointment histories',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(verbose_name='date')),
                ('start_time', models.TimeField(verbose_name='start time')),
                ('end_time', models.TimeField(verbose_name='end time')),
                ('is_available', models.BooleanField(default=True)),
                ('is_blocked', models.BooleanField(default=False)),
                ('blocked_reason', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'time slot',
                'verbose_name_plural': 'time slots',
                'ordering': ['date', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('appointment_number', models.CharField(editable=False, max_length=20, unique=True)),
                ('date', models.DateField(verbose_name='date')),
                ('start_time', models.TimeField(verbose_name='start time')),
                ('end_time', models.TimeField(editable=False, verbose_name='end time')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('confirmed', 'Confirmada'), ('checked_in', 'Check-in Realizado'), ('in_progress', 'En Atención'), ('completed', 'Completada'), ('cancelled', 'Cancelada'), ('no_show', 'No Asistió')], default='pending', max_length=20, verbose_name='status')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancellation_reason', models.CharField(blank=True, choices=[('patient_request', 'Solicitud del Paciente'), ('doctor_unavailable', 'Médico No Disponible'), ('clinic_closed', 'Clínica Cerrada'), ('emergency', 'Emergencia'), ('other', 'Otro')], max_length=30, verbose_name='cancellation reason')),
                ('cancellation_notes', models.TextField(blank=True, verbose_name='cancellation notes')),
                ('patient_notes', models.TextField(blank=True, verbose_name='patient notes')),
                ('doctor_notes', models.TextField(blank=True, verbose_name='doctor notes')),
                ('internal_notes', models.TextField(blank=True, verbose_name='internal notes')),
                ('reminder_sent_24h', models.BooleanField(default=False)),
                ('reminder_sent_1h', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_appointments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'appointment',
                'verbose_name_plural': 'appointments',
                'ordering': ['-date', '-start_time'],
            },
        ),
    ]
